2025-05-18 23:47:06,400 INFO    MainThread:19015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-05-18 23:47:06,402 INFO    MainThread:19015 [wandb_setup.py:_flush():67] Configure stats pid to 19015
2025-05-18 23:47:06,402 INFO    MainThread:19015 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/.config/wandb/settings
2025-05-18 23:47:06,402 INFO    MainThread:19015 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/settings
2025-05-18 23:47:06,402 INFO    MainThread:19015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-18 23:47:06,403 INFO    MainThread:19015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/run-20250518_234706-03o543qb/logs/debug.log
2025-05-18 23:47:06,403 INFO    MainThread:19015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/run-20250518_234706-03o543qb/logs/debug-internal.log
2025-05-18 23:47:06,403 INFO    MainThread:19015 [wandb_init.py:init():761] calling init triggers
2025-05-18 23:47:06,404 INFO    MainThread:19015 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'batch_size': 256, 'native': 'hi', 'model': 'lstm', 'enc_embedding_dim': 128, 'enc_dim': 128, 'n_encoders': 2, 'dec_embedding_dim': 64, 'dec_dim': 512, 'n_decoders': 2, 'linear_dim': 512, 'dropout_rate': 0, 'epochs': 20, 'use_attn': True, 'momentum': 0.9, 'beam_size': 1, 'activation': 'relu', 'optimizer': 'adam', 'learning_rate': 0.001, 'wandb': True, 'wandb_entity': 'da24d008-iit-madras', 'wandb_project': 'da6401-assignment3', 'wandb_sweep': False, 'sweep_id': None, '_wandb': {}}
2025-05-18 23:47:06,404 INFO    MainThread:19015 [wandb_init.py:init():784] starting backend
2025-05-18 23:47:06,404 INFO    MainThread:19015 [wandb_init.py:init():788] sending inform_init request
2025-05-18 23:47:06,501 INFO    MainThread:19015 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-18 23:47:06,502 INFO    MainThread:19015 [wandb_init.py:init():803] backend started and connected
2025-05-18 23:47:06,506 INFO    MainThread:19015 [wandb_init.py:init():896] updated telemetry
2025-05-18 23:47:06,540 INFO    MainThread:19015 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-18 23:47:07,107 INFO    MainThread:19015 [wandb_init.py:init():995] starting run threads in backend
2025-05-18 23:47:07,313 INFO    MainThread:19015 [wandb_run.py:_console_start():2377] atexit reg
2025-05-18 23:47:07,313 INFO    MainThread:19015 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-18 23:47:07,315 INFO    MainThread:19015 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-18 23:47:07,315 INFO    MainThread:19015 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-18 23:47:07,317 INFO    MainThread:19015 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-18 23:48:07,923 INFO    MainThread:19015 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-05-18 23:49:43,535 INFO    MainThread:19015 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-05-18 23:51:06,166 WARNING MsgRouterThr:19015 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-18 23:51:06,174 INFO    MsgRouterThr:19015 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
