2025-05-20 22:05:50,705 INFO    MainThread:62813 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-05-20 22:05:50,705 INFO    MainThread:62813 [wandb_setup.py:_flush():67] Configure stats pid to 62813
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/.config/wandb/settings
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_setup.py:_flush():67] Loading settings from /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/settings
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/run-20250520_220550-l6t5vuab/logs/debug.log
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/rudra_sarkar/Documents/PhD IIT Madras/Intro to Deep Learning M Khapra DA6401/da6401_assignment_3/wandb/run-20250520_220550-l6t5vuab/logs/debug-internal.log
2025-05-20 22:05:50,706 INFO    MainThread:62813 [wandb_init.py:init():761] calling init triggers
2025-05-20 22:05:50,707 INFO    MainThread:62813 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'batch_size': 128, 'native': 'hi', 'model': 'lstm', 'enc_embedding_dim': 64, 'enc_dim': 512, 'n_encoders': 1, 'dec_embedding_dim': 64, 'dec_dim': 512, 'n_decoders': 1, 'linear_dim': 2048, 'dropout_rate': 0.4, 'epochs': 20, 'use_attn': True, 'log_connectivity': False, 'momentum': 0.9359397750924344, 'beam_size': 3, 'activation': 'relu', 'optimizer': 'adamw', 'learning_rate': 0.003190691348613236, 'use_v2': False, 'use_test': False, 'wandb': True, 'wandb_entity': 'da24d008-iit-madras', 'wandb_project': 'da6401-assignment3', 'wandb_sweep': False, 'sweep_id': None, '_wandb': {}}
2025-05-20 22:05:50,707 INFO    MainThread:62813 [wandb_init.py:init():784] starting backend
2025-05-20 22:05:50,707 INFO    MainThread:62813 [wandb_init.py:init():788] sending inform_init request
2025-05-20 22:05:51,075 INFO    MainThread:62813 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-20 22:05:51,076 INFO    MainThread:62813 [wandb_init.py:init():803] backend started and connected
2025-05-20 22:05:51,082 INFO    MainThread:62813 [wandb_init.py:init():896] updated telemetry
2025-05-20 22:05:51,113 INFO    MainThread:62813 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-20 22:05:51,768 INFO    MainThread:62813 [wandb_init.py:init():995] starting run threads in backend
2025-05-20 22:05:51,972 INFO    MainThread:62813 [wandb_run.py:_console_start():2377] atexit reg
2025-05-20 22:05:51,973 INFO    MainThread:62813 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-20 22:05:51,974 INFO    MainThread:62813 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-20 22:05:51,974 INFO    MainThread:62813 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-20 22:05:51,976 INFO    MainThread:62813 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-20 22:06:00,106 WARNING MsgRouterThr:62813 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nlp_env/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-20 22:06:00,107 INFO    MsgRouterThr:62813 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
